[workspace]
members = [
    "common",
    "cli",
    "lsp-common",
]
exclude = [
    "lsp-wasi"
]

[patch.crates-io]
#seedwing-policy-engine = { path = "../seedwing-policy/engine" }
seedwing-policy-engine = { git = "https://github.com/seedwing-io/seedwing-policy", rev = "06eb6b8a97795cf8610d580bb8f47386c05e4162" }
