[patch.crates-io]
# seedwing-policy-engine = { path = "../seedwing-policy/seedwing-policy-engine" }
seedwing-policy-engine = { git = "https://github.com/seedwing-io/seedwing-policy", rev = "d946d0efcd924d23bd4ffe4258eefa233862c4ee" }

[workspace]
members = [
    "seedwing-enforcer",
    "seedwing-enforcer-lsp",
    "seedwing-enforcer-lsp-common",
]
exclude = [
    "seedwing-enforcer-lsp-wasm"
]
